### ISSUE TITLE
Can't compile the project in Android Studio

### ISSUE THREAD

**Issue by AyalaSaenzJorge** [googlesamples/android-sunflower#233] opened 2018-10-26 03:04 UTC
Hi, I've tried this code in both Android Studio 3.2 and 3.3, but I get always this result
![image](https://user-images.githubusercontent.com/31878954/47542186-e0580800-d8a1-11e8-9dc8-dafb3fe4feb6.png)

Thanks in advance.

**Comment by corjohnson** [comment] 2018-10-31 01:14
Do you have more information; such as what version of Kotlin you're running?

**Comment by AyalaSaenzJorge** [comment] 2018-11-01 17:42
Hi, sorry for the delay, as for the Kotin version here is a snapshot of the gradle file with that information:

![image](https://user-images.githubusercontent.com/31878954/47868784-20077e00-ddd3-11e8-97a0-e72fe23cb32e.png)

I'm using:

Android Studio 3.2.1
Build #AI-181.5540.7.32.5056338, built on October 8, 2018
JRE: 1.8.0_152-release-1136-b06 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.4.0-138-generic

**Comment by XinyueZ** [comment] 2018-11-05 19:40
I have AS 3.4.0-alpha02, it works at my side.
Your need pull from latest from the master, what I'd suggest.

**Comment by tiembo** [comment] 2018-11-06 17:29
@AyalaSaenzJorge are you still having this problem?  I am unable to reproduce it with Android Studio 3.2.1 on Linux.

**Comment by AyalaSaenzJorge** [comment] 2018-11-11 22:50
@tiembo yes I do. But I haven't tried @XinyueZ suggestion yet...

**Comment by fidschau** [comment] 2018-11-30 11:07
I had to revert to 0a39e7b639e069c20203c25f2ff6a4e0b86feb62 "Use Kotlin Coroutines for IO executor #235 " for mine to work. I suspect my android studio was battling with gradle 5.0

**Comment by tiembo** [comment] 2018-11-30 18:50
Hi @fidschau - indeed, there was an issue with Gradle 5.0 and Android Studio 3.2.1.  This was fixed in #252, so now the code is back to running Gradle 4.10.2.

@AyalaSaenzJorge I'll go ahead and close this issue.  Please comment if you run into any more problems with your setup.

**Closed by tiembo** 2018-11-30 18:50 UTC
