### ISSUE TITLE
Prevent fragment recreation

### ISSUE THREAD

**Issue by vise950** [googlesamples/android-sunflower#117] opened 2018-07-18 12:49 UTC
When I click on the same drawer item, how can I avoid instantiating the same fragment again?

**Comment by andhie** [comment] 2018-07-19 16:23
based on the Navigation lib code, it will always transact even when clicked the same item. the material guideline did not specify the behaviour when clicking on an already selected item.
maybe you should file an issue at https://issuetracker.google.com/

**Comment by tiembo** [comment] 2018-07-19 23:02
Google issue tracker link: https://issuetracker.google.com/issues/111631295, which is marked as a duplicate of https://issuetracker.google.com/issues/109856764, which is closed as "Intended behavior".

**Closed by tiembo** 2018-07-19 23:02 UTC
