### ISSUE TITLE
3rd-party Gradle plug-ins may be the cause

### ISSUE THREAD

**Issue by muyi-yang** [googlesamples/android-sunflower#70] opened 2018-06-27 11:14 UTC
Failed to resolve: junit
Open File

Folder /media/halove/work/demo/android-sunflower/app/build/generated/source/kaptKotlin/debug

Folder /media/halove/work/demo/android-sunflower/app/build/generated/source/kaptKotlin/release

3rd-party Gradle plug-ins may be the cause

my android studio:3.1.2

**Comment by tiembo** [comment] 2018-06-27 19:15
This project requires using the latest version of the Android Studio preview build, which can be downloaded from https://developer.android.com/studio/preview/.

Closing issue as I am unable to reproduce this on Android Studio 3.2 Beta 1.  Please comment again if you run into further issues.

**Closed by tiembo** 2018-06-27 19:15 UTC

**Comment by mrk-han** [comment] 2019-01-09 22:19
@tiembo I'm trying to run connectedTests on a Linux VM with x86_64 emulator, but running into kapt issue. I do not have Android Studio installed, just the SDK. Is this a possibility? I can create a new issue and post full stacktrace there.

**Comment by tiembo** [comment] 2019-01-09 22:22
@mrk-han yes, please open another issue with more details on your setup and we can troubleshoot there.

**Comment by iNoles** [comment] 2019-01-10 02:43
https://issuetracker.google.com/issues/74537216 Fix is in Android Studio 3.2.x

**Comment by mrk-han** [comment] 2019-01-10 15:58
@iNoles We are not using Android Studio, we just download the latest SDK from 

`https://dl.google.com/android/repository/sdk-tools-linux-4333796.zip`

If this were incremented, I assume it may fix the issue but I'm not sure what # it should be. This link is from `https://developer.android.com/studio/#command-tools`

**Comment by mrk-han** [comment] 2019-01-10 20:56
Turns out this was a Java Issue. Reverting to Open-Jdk-8 and adding export `JVM_OPTS="-XX:+IgnoreUnrecognizedVMOptions"` to .bashrc fixed the issue.
