### ISSUE TITLE
There is drawer lag when clicking an item

### ISSUE THREAD

**Issue by Zheentoro** [googlesamples/android-sunflower#228] opened 2018-10-19 17:19 UTC
Why the Navigation Drawer is getting lag if there is no operations with fragment?

**Comment by tiembo** [comment] 2018-10-19 23:13
I think this is a duplicate of #178 - it's not lag, but rather animation.  Is that what you're referring to?

**Comment by tiembo** [comment] 2018-10-24 16:35
Closing issue - please reply if you're running into a problem.

**Closed by tiembo** 2018-10-24 16:35 UTC
