### ISSUE TITLE
Would be useful if test was doing some network request.

### ISSUE THREAD

**Issue by Malachiasz** [googlesamples/android-sunflower#114] opened 2018-07-18 12:16 UTC
I wanted to see how you implement repository, but was disappointed to see that database is your single data source.

**Comment by andhie** [comment] 2018-07-20 04:58
you may refer to https://github.com/googlesamples/android-architecture-components/tree/master/PagingWithNetworkSample

**Comment by tiembo** [comment] 2018-07-20 05:17
Marking as dupe of #6

**Closed by tiembo** 2018-07-20 05:17 UTC
