### ISSUE TITLE
supportLibraryVersion -> 28.0.0-rc02

### ISSUE THREAD

**Issue by XinyueZ** [googlesamples/android-sunflower#161] opened 2018-08-28 09:03 UTC
Still problem to update support library to 28.0.0-rc02
see:
````
* What went wrong:
Could not resolve all files for configuration ':app:debugCompileClasspath'.
> Could not find com.android.support:design:28.0.0-rc02.
  Searched in the following locations:
    - file:/Users/ /Library/Android/sdk/extras/m2repository/com/android/support/design/28.0.0-rc02/design-28.0.0-rc02.pom
    - file:/Users/ /Library/Android/sdk/extras/m2repository/com/android/support/design/28.0.0-rc02/design-28.0.0-rc02.jar
    - file:/Users/ /Library/Android/sdk/extras/google/m2repository/com/android/support/design/28.0.0-rc02/design-28.0.0-rc02.pom
    - file:/Users/ /Library/Android/sdk/extras/google/m2repository/com/android/support/design/28.0.0-rc02/design-28.0.0-rc02.jar
    - file:/Users/ /Library/Android/sdk/extras/android/m2repository/com/android/support/design/28.0.0-rc02/design-28.0.0-rc02.pom
    - file:/Users/ /Library/Android/sdk/extras/android/m2repository/com/android/support/design/28.0.0-rc02/design-28.0.0-rc02.jar
    - https://dl.google.com/dl/android/maven2/com/android/support/design/28.0.0-rc02/design-28.0.0-rc02.pom
    - https://dl.google.com/dl/android/maven2/com/android/support/design/28.0.0-rc02/design-28.0.0-rc02.jar
    - https://jcenter.bintray.com/com/android/support/design/28.0.0-rc02/design-28.0.0-rc02.pom
    - https://jcenter.bintray.com/com/android/support/design/28.0.0-rc02/design-28.0.0-rc02.jar
  Required by:
      project :app
> Could not find com.android.support:design:28.0.0-rc02.
  Searched in the following locations:
    - file:/Users/ /Library/Android/sdk/extras/m2repository/com/android/support/design/28.0.0-rc02/design-28.0.0-rc02.pom
    - file:/Users/ /Library/Android/sdk/extras/m2repository/com/android/support/design/28.0.0-rc02/design-28.0.0-rc02.jar
    - file:/Users/ /Library/Android/sdk/extras/google/m2repository/com/android/support/design/28.0.0-rc02/design-28.0.0-rc02.pom
    - file:/Users/ /Library/Android/sdk/extras/google/m2repository/com/android/support/design/28.0.0-rc02/design-28.0.0-rc02.jar
    - file:/Users/ /Library/Android/sdk/extras/android/m2repository/com/android/support/design/28.0.0-rc02/design-28.0.0-rc02.pom
    - file:/Users/ /Library/Android/sdk/extras/android/m2repository/com/android/support/design/28.0.0-rc02/design-28.0.0-rc02.jar
    - https://dl.google.com/dl/android/maven2/com/android/support/design/28.0.0-rc02/design-28.0.0-rc02.pom
    - https://dl.google.com/dl/android/maven2/com/android/support/design/28.0.0-rc02/design-28.0.0-rc02.jar
    - https://jcenter.bintray.com/com/android/support/design/28.0.0-rc02/design-28.0.0-rc02.pom
    - https://jcenter.bintray.com/com/android/support/design/28.0.0-rc02/design-28.0.0-rc02.jar
  Required by:
      project :app > android.arch.navigation:navigation-ui-ktx:1.0.0-alpha05 > android.arch.navigation:navigation-ui:1.0.0-alpha05
```

**Comment by tiembo** [comment] 2018-08-28 20:52
Marking this as a dupe of #2, as we want to migrate to AndroidX once nav-ktx is supported.

**Closed by tiembo** 2018-08-28 20:52 UTC

**Comment by XinyueZ** [comment] 2018-08-29 15:31
@tiembo, I know that  the project should be switched to Androidx, however, a lot of projects have to use support namespace in product. I have created an issue, please info Google stuff for some solutions. 
https://issuetracker.google.com/issues/113346929
Thanks.
